### ISSUE TITLE
Question: Why did you swap out the camera?

### ISSUE THREAD

**Issue by jim-at-jibba** [traumverloren/crow-detector#4]
Hey, 

I was just wondering why you swapped out the camera. I want to build something similar and only have the standard camera v2 module and wondered if it would work.

Thanks

**Comment by traumverloren** [comment]
I switched because I wanted to try the new camera and lenses. the standard camera works, the new one is just better.

**Comment by jim-at-jibba** [comment]
Ace thanks for the info. I love your hardware projects
